global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'render-intellmeet-backend'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['intellmeet-backend-5j5a.onrender.com']
